import { Printer, RefreshCcw, Save, ZoomIn, ZoomOut } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  getInvoiceTemplateSettings,
  getInvoiceTemplates,
  previewInvoiceTemplate,
  updateInvoiceTemplateSettings
} from "../api/invoiceTemplates";
import { Button } from "../components/Button";
import { CommonBreadcrumb } from "../components/CommonBreadcrumb";
import { GlassCard } from "../components/GlassCard";
import { Header } from "../components/Header";
import { Input } from "../components/Input";
import { Select } from "../components/Select";
import { useApiMessage } from "../hooks/useApiFeedback";
import { CommonSuccessMessageUtil } from "../lib/CommonSuccessMessageUtil";
import { notificationService } from "../services/notificationService";
import type { CompanyInvoiceSettings, InvoiceTemplateMetadata } from "../types/api";

const emptySettings: CompanyInvoiceSettings = {
  defaultTemplateId: "",
  showWatermark: false,
  watermarkText: "",
  showSignature: true,
  signatureLabel: "Authorized Signature",
  signatureHeading: "For Company",
  showQr: true,
  showBankDetails: true,
  showTerms: true,
  showNotes: true,
  noteText: "Thank you for choosing BizFinity.",
  termsText: "Goods once sold will not be taken back.",
  footerCredit: "Generated by BizFinity Billing SaaS"
};

export const InvoiceTemplatesPage = () => {
  const { setApiError, clearMessage } = useApiMessage();
  const [templates, setTemplates] = useState<InvoiceTemplateMetadata[]>([]);
  const [settings, setSettings] = useState<CompanyInvoiceSettings>(emptySettings);
  const [selectedTemplateId, setSelectedTemplateId] = useState("");
  const [previewHtml, setPreviewHtml] = useState("");
  const [previewName, setPreviewName] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [loadingPreview, setLoadingPreview] = useState(false);
  const [zoom, setZoom] = useState(1);
  const iframeRef = useRef<HTMLIFrameElement | null>(null);

  const selectedTemplate = useMemo(
    () => templates.find((template) => template.templateId === selectedTemplateId) ?? null,
    [selectedTemplateId, templates]
  );

  const loadPreview = useCallback(
    async (templateId: string, nextSettings: CompanyInvoiceSettings) => {
      if (!templateId) {
        setPreviewHtml("");
        setPreviewName("");
        return;
      }
      try {
        setLoadingPreview(true);
        const preview = await previewInvoiceTemplate(templateId, {
          showWatermark: nextSettings.showWatermark,
          watermarkText: nextSettings.watermarkText ?? undefined,
          showSignature: nextSettings.showSignature,
          signatureLabel: nextSettings.signatureLabel ?? undefined,
          signatureHeading: nextSettings.signatureHeading ?? undefined,
          showQr: nextSettings.showQr,
          showBankDetails: nextSettings.showBankDetails,
          showTerms: nextSettings.showTerms,
          showNotes: nextSettings.showNotes,
          noteText: nextSettings.noteText ?? undefined,
          termsText: nextSettings.termsText ?? undefined,
          footerCredit: nextSettings.footerCredit ?? undefined
        });
        setPreviewHtml(preview.html);
        setPreviewName(preview.templateName);
      } catch (error: any) {
        setApiError(error, "Unable to preview invoice template");
      } finally {
        setLoadingPreview(false);
      }
    },
    [setApiError]
  );

  useEffect(() => {
    void Promise.all([getInvoiceTemplates(), getInvoiceTemplateSettings()])
      .then(([templateRows, settingsRow]) => {
        setTemplates(templateRows);
        const defaultTemplateId = settingsRow.defaultTemplateId || templateRows[0]?.templateId || "";
        setSettings({
          ...emptySettings,
          ...settingsRow,
          defaultTemplateId
        });
        setSelectedTemplateId(defaultTemplateId);
      })
      .catch((error: any) => setApiError(error, "Unable to load invoice templates"))
      .finally(() => setLoading(false));
  }, [setApiError]);

  useEffect(() => {
    if (!selectedTemplateId) {
      return;
    }
    const timeoutId = window.setTimeout(() => {
      void loadPreview(selectedTemplateId, settings);
    }, 180);
    return () => window.clearTimeout(timeoutId);
  }, [
    loadPreview,
    selectedTemplateId,
    settings.showWatermark,
    settings.watermarkText,
    settings.showSignature,
    settings.signatureLabel,
    settings.signatureHeading,
    settings.showQr,
    settings.showBankDetails,
    settings.showTerms,
    settings.showNotes,
    settings.noteText,
    settings.termsText,
    settings.footerCredit
  ]);

  const save = async () => {
    clearMessage();
    try {
      setSaving(true);
      const saved = await updateInvoiceTemplateSettings({
        ...settings,
        watermarkText: settings.watermarkText ?? undefined,
        signatureLabel: settings.signatureLabel ?? undefined,
        signatureHeading: settings.signatureHeading ?? undefined,
        noteText: settings.noteText ?? undefined,
        termsText: settings.termsText ?? undefined,
        footerCredit: settings.footerCredit ?? undefined
      });
      setSettings(saved);
      notificationService.showSuccess(CommonSuccessMessageUtil.updated("Invoice Template Settings"));
      const refreshedTemplates = await getInvoiceTemplates();
      setTemplates(refreshedTemplates);
    } catch (error: any) {
      setApiError(error, "Unable to save invoice template settings");
    } finally {
      setSaving(false);
    }
  };

  const printPreview = () => {
    const frame = iframeRef.current?.contentWindow;
    if (!frame) {
      notificationService.showError("Preview is not ready for printing yet.");
      return;
    }
    frame.focus();
    frame.print();
  };

  const zoomOut = () => setZoom((current) => Math.max(0.3, Number((current - 0.1).toFixed(2))));
  const zoomIn = () => setZoom((current) => Math.min(1.6, Number((current + 0.1).toFixed(2))));
  const zoomLabel = `${Math.round(zoom * 100)}%`;
  const iframeWidth = `${100 / zoom}%`;
  const iframeHeight = `${980 / zoom}px`;

  return (
    <div className="space-y-4 pb-6">
      <Header title="Invoice Templates" subtitle="Choose the default invoice template and preview a compact one-page invoice before using it for print, PDF, email, and WhatsApp." />
      <GlassCard className="space-y-4 p-6 md:p-7">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <CommonBreadcrumb items={[{ label: "Setup" }, { label: "Invoice Templates" }]} />
          <div className="flex gap-2">
            <Button type="button" variant="secondary" disabled={loadingPreview || !selectedTemplateId} onClick={() => void loadPreview(selectedTemplateId, settings)}>
              <RefreshCcw size={16} />
              Refresh Preview
            </Button>
            <Button type="button" variant="secondary" disabled={!previewHtml} onClick={printPreview}>
              <Printer size={16} />
              Print Preview
            </Button>
            <Button type="button" disabled={saving || !settings.defaultTemplateId} onClick={() => void save()}>
              <Save size={16} />
              {saving ? "Saving..." : "Save Default"}
            </Button>
          </div>
        </div>

        {loading ? (
          <div className="rounded-2xl border border-slate-200 bg-slate-50 p-6 text-sm text-slate-500">Loading invoice templates...</div>
        ) : (
          <div className="grid gap-4 xl:grid-cols-[320px_minmax(0,1fr)]">
            <GlassCard className="space-y-4 p-4">
              <Select
                label="Default Template"
                placeholder={null}
                value={settings.defaultTemplateId}
                options={templates.map((template) => ({ label: template.templateName, value: template.templateId }))}
                onChange={(event) => {
                  setSettings((current) => ({ ...current, defaultTemplateId: event.target.value }));
                  setSelectedTemplateId(event.target.value);
                }}
              />
              {selectedTemplate ? (
                <div className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3">
                  <p className="text-sm font-bold text-slate-900">{selectedTemplate.templateName}</p>
                  <p className="mt-1 text-xs text-slate-500">{selectedTemplate.description}</p>
                  <p className="mt-2 text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-400">Version {selectedTemplate.version}</p>
                </div>
              ) : null}
              <div className="grid gap-3">
                <Toggle label="Show Watermark" value={settings.showWatermark} onChange={(value) => setSettings((current) => ({ ...current, showWatermark: value }))} />
                {settings.showWatermark ? (
                  <Input
                    label="Watermark Label"
                    value={settings.watermarkText ?? ""}
                    onChange={(event) => setSettings((current) => ({ ...current, watermarkText: event.target.value }))}
                  />
                ) : null}
                <Toggle label="Show Signature" value={settings.showSignature} onChange={(value) => setSettings((current) => ({ ...current, showSignature: value }))} />
                {settings.showSignature ? (
                  <>
                    <Input
                      label="Signature Heading"
                      value={settings.signatureHeading ?? ""}
                      onChange={(event) => setSettings((current) => ({ ...current, signatureHeading: event.target.value }))}
                    />
                    <Input
                      label="Signature Label"
                      value={settings.signatureLabel ?? ""}
                      onChange={(event) => setSettings((current) => ({ ...current, signatureLabel: event.target.value }))}
                    />
                  </>
                ) : null}
                <Toggle label="Show Terms" value={settings.showTerms} onChange={(value) => setSettings((current) => ({ ...current, showTerms: value }))} />
                {settings.showTerms ? (
                  <TextAreaField
                    label="Terms & Conditions"
                    value={settings.termsText ?? ""}
                    onChange={(value) => setSettings((current) => ({ ...current, termsText: value }))}
                  />
                ) : null}
                <Toggle label="Show Notes" value={settings.showNotes} onChange={(value) => setSettings((current) => ({ ...current, showNotes: value }))} />
                {settings.showNotes ? (
                  <TextAreaField
                    label="Notes"
                    value={settings.noteText ?? ""}
                    onChange={(value) => setSettings((current) => ({ ...current, noteText: value }))}
                  />
                ) : null}
                <Input
                  label="Footer Credit"
                  value={settings.footerCredit ?? ""}
                  onChange={(event) => setSettings((current) => ({ ...current, footerCredit: event.target.value }))}
                />
              </div>
            </GlassCard>

            <GlassCard className="space-y-4 p-4">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <p className="text-xs font-bold uppercase tracking-[0.2em] text-slate-400">Preview</p>
                  <h3 className="mt-1 text-xl font-extrabold text-slate-950">{previewName || selectedTemplate?.templateName || "Invoice Template"}</h3>
                  <p className="mt-1 text-sm text-slate-500">Compact demo invoice preview with reduced empty space.</p>
                </div>
                <div className="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-white px-2 py-1 shadow-sm">
                  <Button type="button" variant="ghost" className="min-h-8 px-2 py-1" disabled={zoom <= 0.3} onClick={zoomOut}>
                    <ZoomOut size={16} />
                  </Button>
                  <span className="min-w-12 text-center text-xs font-bold text-slate-600">{zoomLabel}</span>
                  <Button type="button" variant="ghost" className="min-h-8 px-2 py-1" disabled={zoom >= 1.6} onClick={zoomIn}>
                    <ZoomIn size={16} />
                  </Button>
                </div>
              </div>
              <div className="rounded-[28px] border border-slate-200 bg-slate-100 p-3">
                {loadingPreview ? <div className="mb-3 rounded-2xl bg-white/80 px-4 py-2 text-sm font-medium text-slate-500">Refreshing preview with current template settings...</div> : null}
                <div className="overflow-auto rounded-[24px] border border-slate-200 bg-white">
                  <iframe
                    ref={iframeRef}
                    title={previewName || "Invoice template preview"}
                    srcDoc={previewHtml}
                    className="preview-surface rounded-[24px] border-0 bg-white"
                    style={{
                      width: iframeWidth,
                      height: iframeHeight,
                      transform: `scale(${zoom})`,
                      transformOrigin: "top center"
                    }}
                  />
                </div>
              </div>
            </GlassCard>
          </div>
        )}
      </GlassCard>
    </div>
  );
};

const Toggle = ({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) => (
  <label className="flex items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700">
    <span>{label}</span>
    <input type="checkbox" checked={value} onChange={(event) => onChange(event.target.checked)} />
  </label>
);

const TextAreaField = ({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) => (
  <label className="space-y-2 rounded-2xl border border-slate-200 bg-white px-4 py-3">
    <span className="block text-sm font-semibold text-slate-700">{label}</span>
    <textarea
      value={value}
      onChange={(event) => onChange(event.target.value)}
      rows={3}
      className="w-full resize-y rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-700 outline-none transition focus:border-[var(--theme-color)] focus:bg-white"
    />
  </label>
);
